
@host = http://localhost:4004
@auth = Basic pirate:ahoy
@model = text-davinci-003

# DELETE {{host}}/ai2report/Records( ID = 'f0f132c6-a3d3-48ea-be80-ad488fc4c172' ) 

# # Call the function to get the list of OpenAI models
# POST {{host}}/ai2report/Chats
# Content-Type: application/json



# # Call the function to get the list of OpenAI models
 POST {{host}}/ai2report/Chats(5e629bad-9e32-4b36-a105-70b132232b2f)/newRecord
 Content-Type: application/json

{"content": "设计一张销售发票报表"}


#  POST {{host}}/ai2report/Records(6032d796-2c20-4ea3-bb9a-04c0f761adc0)/adopt
#  Content-Type: application/json


#  POST {{host}}/ai2report/Reports(e617b4e2-cb21-40cb-ac5f-adb078094a39)/verify
#  Content-Type: application/json


